In [8]:
#Task 4.1 (1. Initialize an empty array with size 2X2.)
import numpy as np
a = np.ones((2, 2))
print(a)


[[1. 1.]
 [1. 1.]]


In [7]:
#Task 4.2 (2. Initialize an all one array with size 4X2.)
import numpy as np
a = np.ones((4, 2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
#Task 4.3 (Return a new array of given shape and type, filled with fill value.{Hint: np.full}
import numpy as np
a= np.full((4, 2), 6)
print(a)

[[6 6]
 [6 6]
 [6 6]
 [6 6]]


In [11]:
#Task 4.4 (Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])
zeros = np.zeros_like(array)
print(zeros)


[[0 0 0]
 [0 0 0]]


In [16]:
#Task 4.5 (Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
zeros = np.ones_like(a)
print(zeros)

[[1 1 1]
 [1 1 1]]


In [17]:
#Task 4.6 (For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
import numpy as np
new_list = [1, 2, 3, 4]
a = np.array(new_list)
print(a)

[1 2 3 4]


In [19]:
#Task 4.1.1
#Array Manipulation: Numerical Ranges and Array indexing:
#Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
import numpy as np
a = np.arange(10, 50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [27]:
#Create a 3X3 matrix with values ranging from 0 to 8. {Hint:look for np.reshape()}
import numpy as np
array = np.arange(9)
matrix = array.reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
#Task 4.1.1.3
#Create a 3X3 identity matrix.{Hint:np.eye()}
import numpy as np
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
#Task 4.1.5 (Create a 10X10 array with random values and find the minimum and maximum values.)
import numpy as np
random_array = np.random.random((10, 10))
min = random_array.min()
max = random_array.max()
print(random_array)
print ("Min: ", min)
print("Max: ", max)


[[0.02239654 0.25848965 0.384189   0.25254516 0.86487049 0.12043914
  0.72598708 0.78123181 0.59972235 0.78163752]
 [0.57903625 0.88464359 0.57967899 0.62430666 0.47927291 0.17778259
  0.87862529 0.15313983 0.9800176  0.96560457]
 [0.74379907 0.93976696 0.91427057 0.46932811 0.5725156  0.00966859
  0.32049205 0.24802104 0.70225579 0.29788939]
 [0.94843745 0.15227978 0.27557417 0.16423324 0.9065525  0.50623681
  0.10492435 0.42634174 0.34635284 0.25279085]
 [0.90377617 0.46372633 0.08732729 0.92653684 0.16662809 0.25623857
  0.75030689 0.45536025 0.45422752 0.12899771]
 [0.95500283 0.66455019 0.2914833  0.90360035 0.3136355  0.2737536
  0.84829277 0.21768983 0.21412604 0.26216133]
 [0.3595171  0.18892137 0.61073191 0.46299635 0.42676719 0.19255465
  0.36736277 0.85690683 0.43448049 0.65345723]
 [0.76137805 0.75590393 0.78482294 0.57543314 0.12320884 0.7577817
  0.53431948 0.92841887 0.18162245 0.22291857]
 [0.8880965  0.94233312 0.4250085  0.93630712 0.97838339 0.17565415
  0.44684849 0

In [33]:
#Create a zero array of size 10 and replace 5th element with 1.
import numpy as np
array = np.zeros(10)
array[4] = 1
print(array)

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [35]:
#Reverse an array arr = [1,2,0,0,4,0].
arr = [1, 2, 0, 0, 4, 0]
reversed = arr[::-1]
print(reversed)

[0, 4, 0, 0, 2, 1]


In [44]:
#8. Create a 2d array with 1 on border and 0 inside.
import numpy as np
size = 5
array = np.ones((size, size))
array[1:-1, 1:-1] = 0  #It sets the inner elements (excluding the border) to 0 using slicing.
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [48]:
#2nd Try
import numpy as np
array = np.ones((4,4))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [55]:
#Create a 8X8 matrix and fill it with a checkerboard pattern.
import numpy as np
checker = np.zeros((8, 8), dtype=int)
checker[::2, ::2] = 1  # Set every other element in even rows and columns to 1
checker[1::2, 1::2] = 1  # Set every other element in odd rows and columns to 1
print(checker)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [62]:
 # Problem - 3: Array Operations:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_result = x + y
print("1. Add:")
print(add_result)

# 2. Subtract the two arrays
subtract_result = x - y
print("\n2. Subtract:")
print(subtract_result)

# 3. Multiply the array with any integers of your choice
multiply_x = x * 2
multiply_y = y * 2
print("\n3. Multiply the arrays by 2:")
print("x * 2:")
print(multiply_x)
print("y * 2:")
print(multiply_y)

# 4. Find the square of each element of the array
square_x = np.square(x)
square_y = np.square(y)
print("\n4. Square of each element of the array:")
print("Square of x:")
print(square_x)
print("Square of y:")
print(square_y)

# 5. Find the dot product between:
# - v and w
# - x and v
# - x and y
dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)
print("\n5. Dot product results:")
print(f"Dot product between v and w: {dot_v_w}")
print(f"Dot product between x and v: {dot_x_v}")
print(f"Dot product between x and y: {dot_x_y}")

# 6. Concatenate x and y along row and concatenate v and w along column
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_column = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)

print("\n6. Concatenate results:")
print("Concatenate x and y along row:")
print(concat_xy_row)
print("Concatenate v and w along column:")
print(concat_vw_column)

1. Add:
[[ 6  8]
 [10 13]]

2. Subtract:
[[-4 -4]
 [-4 -3]]

3. Multiply the arrays by 2:
x * 2:
[[ 2  4]
 [ 6 10]]
y * 2:
[[10 12]
 [14 16]]

4. Square of each element of the array:
Square of x:
[[ 1  4]
 [ 9 25]]
Square of y:
[[25 36]
 [49 64]]

5. Dot product results:
Dot product between v and w: 219
Dot product between x and v: [29 77]
Dot product between x and y: [[19 22]
 [50 58]]

6. Concatenate results:
Concatenate x and y along row:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column:
[[ 9 11]
 [10 12]]


In [ ]:
#ValueError: all the input arrays must have same number of dimensions
#When we try to concatenate these arrays along axis=0 (i.e., row-wise), NumPy expects both arrays to have the same number of dimensions. However, x is 2D (shape (2, 2)) and v is 1D (shape (2,)), so NumPy can't concatenate them directly

In [67]:
import numpy as np
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
result_A_inv = np.dot(A, A_inv)
print("result: ")
print(result_A_inv)

AB = np.dot(A, B)
BA = np.dot(B, A)
print("not proved:")
print("AB =\n", AB)
print("BA =\n", BA)

AB_T = np.transpose(AB)
B_T_A_T = np.dot(np.transpose(B), np.transpose(A))
print("\n3. Prove (AB)^T = B^T A^T:")
print("Transpose of AB =\n", AB_T)
print("B^T * A^T =\n", B_T_A_T)

A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])

B_eq = np.array([-1, -3, 9])

A_eq_inv = np.linalg.inv(A_eq)
X = np.dot(A_eq_inv, B_eq)

print("\n4. Solution of the system of equations using Inverse Method:")
print(f"Solution (x, y, z): {X}")

result: 
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
not proved:
AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]

3. Prove (AB)^T = B^T A^T:
Transpose of AB =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]

4. Solution of the system of equations using Inverse Method:
Solution (x, y, z): [ 2.  1. -2.]
